import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "@/components/shell/AppShell";
import { WorkflowFeedback } from "@/components/forms/WorkflowFeedback";
import { getApprovalPeriod } from "@/lib/forms/workflow";
import { approvePeriodAction, returnPeriodAction } from "../../actions";

export const dynamic = "force-dynamic";
export default async function ReviewPage({ params, searchParams }: { params: Promise<{periodId:string}>; searchParams: Promise<{error?:string}> }) {
  const { periodId } = await params; const query=await searchParams; const data=await getApprovalPeriod(periodId); if(!data) notFound();
  const {period,summary,exceptions}=data; const template=period.form_template_versions.form_templates;
  return <AppShell headerTitle="Duyệt / Chốt kỳ"><Link href="/approvals" className="text-sm font-bold text-blue-800">← Hàng đợi phê duyệt</Link><p className="mt-5 text-xs font-bold text-blue-800">{template.code} · {period.status}</p><h1 className="mt-1 text-3xl font-bold">{template.name}</h1><p className="mt-2 text-slate-600">{period.period_label} · {period.locations?.name ?? period.assets?.source_name ?? "Toàn khoa"}</p><WorkflowFeedback error={query.error}/><section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-6">{[["Tổng",summary.total],["Đã làm",summary.completed],["N/A",summary.na],["Còn thiếu",summary.pending],["Bất thường",summary.abnormal],["Máy H",summary.broken]].map(([label,count])=><div key={label} className="rounded-2xl border bg-white p-4"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{count}</p></div>)}</section><section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Ngoại lệ cần rà soát</h2><div className="mt-3 space-y-2">{exceptions.map(item=><div key={`${item.type}-${item.id}`} className="rounded-xl bg-amber-50 p-3"><b>{item.type}</b><p className="text-sm">{item.label}</p></div>)}{exceptions.length===0?<p className="text-sm text-slate-600">Không có ngoại lệ.</p>:null}</div><Link href={`/periods/${period.id}`} className="mt-4 inline-flex min-h-11 items-center font-bold text-blue-800">Xem toàn bộ ma trận →</Link></section><section className="mt-6 grid gap-4 lg:grid-cols-2"><form action={returnPeriodAction} className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><input type="hidden" name="periodId" value={period.id}/><input type="hidden" name="lockVersion" value={period.lock_version}/><h2 className="font-bold text-amber-950">Trả lại kỳ</h2><label className="mt-3 block text-sm font-semibold">Lý do trả lại<textarea name="reason" required className="mt-2 min-h-24 w-full rounded-xl border bg-white p-3"/></label><button className="mt-3 min-h-11 rounded-xl border border-amber-600 px-5 font-bold">Trả lại để chỉnh sửa</button></form><form action={approvePeriodAction} className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><input type="hidden" name="periodId" value={period.id}/><input type="hidden" name="lockVersion" value={period.lock_version}/><h2 className="font-bold text-emerald-950">Phê duyệt điện tử trong hệ thống</h2><p className="mt-2 text-sm text-emerald-900">Xác nhận kỳ đã đầy đủ và chuyển sang chỉ đọc.</p><button disabled={summary.pending>0 || period.status!=="READY_FOR_REVIEW"} className="mt-5 min-h-11 rounded-xl bg-emerald-800 px-5 font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">Phê duyệt kỳ</button></form></section></AppShell>;
}
