import { BarChart3 } from "lucide-react";

export type ChartPoint = { label: string; value: number };

export function OperationalChart({ title, unit = "", points, description }: { title: string; unit?: string; points: ChartPoint[]; description?: string }) {
  if (!points.length) return <section className="clinical-card p-4" aria-label={title}><div className="flex items-center gap-2"><BarChart3 className="size-5 text-teal-700" /><h2 className="font-extrabold text-slate-950">{title}</h2></div><div className="mt-4 grid min-h-40 place-items-center rounded-2xl border border-dashed border-slate-200 bg-slate-50 px-4 text-center"><div><p className="font-bold text-slate-700">Chưa đủ dữ liệu để vẽ biểu đồ</p><p className="mt-1 text-xs text-slate-500">Biểu đồ chỉ xuất hiện khi có bản ghi thực tế.</p></div></div></section>;
  const max = Math.max(...points.map((point) => point.value));
  const min = Math.min(...points.map((point) => point.value));
  const range = Math.max(max - min, 1);
  const coords = points.map((point, index) => ({ ...point, x: points.length === 1 ? 50 : index / (points.length - 1) * 100, y: 78 - ((point.value - min) / range) * 58 }));
  const path = coords.map((point, index) => `${index ? "L" : "M"}${point.x},${point.y}`).join(" ");
  return <section className="clinical-card p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><BarChart3 className="size-5 text-teal-700" /><h2 className="font-extrabold text-slate-950">{title}</h2></div>{description ? <p className="mt-1 text-xs text-slate-500">{description}</p> : null}</div><span className="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-bold text-teal-800">{points.length} điểm</span></div><div className="mt-4 overflow-x-auto"><div className="min-w-[300px]" role="img" aria-label={`${title}: ${points.map((point) => `${point.label} ${point.value}${unit}`).join(", ")}`}><svg viewBox="0 0 100 90" className="h-44 w-full overflow-visible" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="clinicalChartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#14b8a6" stopOpacity=".28"/><stop offset="100%" stopColor="#14b8a6" stopOpacity="0"/></linearGradient></defs>{[20,49,78].map((y) => <line key={y} x1="0" x2="100" y1={y} y2={y} stroke="#dbeafe" strokeWidth=".5" />)}<path d={`${path} L100,82 L0,82 Z`} fill="url(#clinicalChartFill)"/><path d={path} fill="none" stroke="#0f766e" strokeWidth="2" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round"/>{coords.map((point) => <circle key={`${point.label}-${point.value}`} cx={point.x} cy={point.y} r="2" fill="#fff" stroke="#0f766e" strokeWidth="1.5" vectorEffect="non-scaling-stroke" />)}</svg><div className="-mt-1 grid text-center text-[10px] font-semibold text-slate-500" style={{ gridTemplateColumns: `repeat(${points.length}, minmax(0,1fr))` }}>{points.map((point) => <span key={`${point.label}-axis`} className="truncate px-0.5">{point.label}</span>)}</div></div></div><div className="mt-3 flex flex-wrap gap-2">{points.slice(0,6).map((point) => <span key={`${point.label}-value`} className="rounded-lg bg-slate-50 px-2 py-1 text-xs font-bold text-slate-700"><span className="text-slate-500">{point.label}</span> {point.value}{unit}</span>)}</div></section>;
}

export function StatusDistribution({ title, items }: { title: string; items: Array<{ label: string; value: number; tone: "teal" | "green" | "amber" | "red" | "slate" }> }) {
  const total = items.reduce((sum, item) => sum + item.value, 0);
  const color = { teal: "bg-teal-600", green: "bg-emerald-600", amber: "bg-amber-500", red: "bg-red-500", slate: "bg-slate-400" };
  return <section className="clinical-card p-4"><div className="flex items-center justify-between"><h2 className="font-extrabold text-slate-950">{title}</h2><span className="text-xs font-bold text-slate-500">Tổng {total}</span></div>{total ? <><div className="mt-4 flex h-3 overflow-hidden rounded-full bg-slate-100" role="img" aria-label={`${title}: ${items.map((item) => `${item.label} ${item.value}`).join(", ")}`}>{items.map((item) => item.value ? <span key={item.label} className={color[item.tone]} style={{ width: `${item.value / total * 100}%` }} /> : null)}</div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{items.map((item) => <div key={item.label} className="rounded-xl bg-slate-50 p-2.5"><div className="flex items-center gap-2 text-xs font-semibold text-slate-600"><span className={`size-2.5 rounded-full ${color[item.tone]}`} />{item.label}</div><b className="mt-1 block text-lg text-slate-950">{item.value}</b></div>)}</div></> : <div className="mt-4 rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-5 text-center text-sm font-semibold text-slate-500">Chưa có dữ liệu thực tế</div>}</section>;
}
