import { notFound } from "next/navigation";
import { AppShell } from "@/components/shell/AppShell";
import { getPeriod, type RecordView } from "@/lib/forms/queries";
export const dynamic = "force-dynamic";
function ShiftMatrix({ records }: { records: RecordView[] }) {
  const shifts = records.filter(record => record.record_type === "EQUIPMENT_SHIFT");
  const counts = (record: RecordView) => ({ BT: record.equipment_shift_statuses.filter(x => x.status_code === "BT").length, KSD: record.equipment_shift_statuses.filter(x => x.status_code === "KSD").length, H: record.equipment_shift_statuses.filter(x => x.status_code === "H").length });
  return <div className="space-y-4">{shifts.map(record => { const summary = counts(record); return <article key={record.id} className="rounded-2xl border bg-white p-4"><header className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-bold">{record.business_date} · {record.slot_code}</h2><p className="text-sm font-semibold">BT {summary.BT} · KSD {summary.KSD} · H {summary.H}</p></header><div className="mt-3 grid grid-cols-5 gap-2 sm:grid-cols-10 lg:grid-cols-25">{record.equipment_shift_statuses.sort((a,b)=>a.asset_display_order_snapshot-b.asset_display_order_snapshot).map(item => <div title={item.asset_label_snapshot} key={item.asset_display_order_snapshot} className={`rounded-lg border p-2 text-center text-xs font-bold ${item.status_code === "H" ? "border-red-300 bg-red-50 text-red-900" : item.status_code === "KSD" ? "border-amber-300 bg-amber-50 text-amber-950" : "border-emerald-300 bg-emerald-50 text-emerald-900"}`}><span className="block">#{item.asset_display_order_snapshot}</span>{item.status_code}</div>)}</div></article> })}{shifts.length===0?<p className="rounded-2xl border border-dashed p-8 text-center text-slate-600">Chưa có ca được ghi.</p>:null}</div>;
}
export default async function Page({ params }: { params: Promise<{ periodId: string }> }) {
  const data = await getPeriod((await params).periodId); if (!data) notFound();
  const { period } = data; const template = period.form_template_versions.form_templates; const isBm06 = template.code === "BM.06/QL.TRTB.01";
  const recordMap = new Map(data.records.map(record => [`${record.business_date}:${record.slot_code ?? ""}`, record]));
  return <AppShell headerTitle="Chi tiết kỳ"><p className="text-sm font-bold text-blue-800">{template.code} · {period.status}</p><h1 className="mt-1 text-3xl font-bold">{template.name}</h1><p className="mt-2 text-slate-600">{period.period_label} · {period.locations?.name ?? period.assets?.source_name ?? "Toàn khoa"}</p><div className="mt-6">{isBm06 ? <ShiftMatrix records={data.records}/> : <div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Ngày</th><th className="p-3">Lần/Ca</th><th className="p-3">Trạng thái</th><th className="p-3">Giá trị / Kết quả</th></tr></thead><tbody>{data.occurrences.map(occurrence => { const record = recordMap.get(`${occurrence.business_date}:${occurrence.slot_code ?? ""}`); const detail = record?.measurement_details ?? record?.maintenance_details ?? record?.decontamination_details ?? "—"; return <tr key={occurrence.id} className="border-t"><td className="p-3">{occurrence.business_date ?? "Trong kỳ"}</td><td className="p-3 font-semibold">{occurrence.slot_code}</td><td className="p-3">{occurrence.status}</td><td className="p-3"><code>{typeof detail === "string" ? detail : JSON.stringify(detail)}</code></td></tr> })}</tbody></table></div>}</div></AppShell>;
}
